name: my_package
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: ^3.3.3

dependencies:
  built_version_annotation: ^1.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  build_runner: ^2.4.0
  build_config: ^1.1.0
  built_version: ^1.0.0

# Do not include in your code
dependency_overrides: 
  built_version:
    path: ../built_version
  built_version_annotation:
    path: ../built_version_annotation
