name: built_version
repository: https://github.com/huffSamuel/built_version/tree/main/built_version
description: Generate source code with the package's version by annotating a getter.
version: 1.0.0

environment:
  sdk: ^3.3.3

dependencies:
  analyzer: ^6.4.1
  build: ^2.4.0
  glob: ^2.1.2
  meta: ^1.15.0
  pub_semver: ^2.1.4
  source_gen: ^1.5.0
  built_version_annotation: ^1.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  build_runner: ^2.4.0
  build_config: ^1.1.0
